version: '3'

networks:
  backend:
    driver: bridge

services:
  db:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    networks:
      - backend

  web:
    build: .
    command: python mysite/manage.py runserver 0.0.0.0:8001
    ports:
      - "8001:8001"
    volumes:
      - .:/code
    networks:
      - backend
    depends_on:
      - db
       


